export { default as Home } from './Home'
export { default as About } from './About'
export { default as Authentication } from './Authentication'
export { default as Workshop } from './Workshop'
export { default as Verification } from './Verification'
